USE [master]
GO

/****** Object:  Database [Farm]    Script Date: 10/28/2019 9:51:24 PM ******/
CREATE DATABASE [Farm]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Farm', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Farm.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Farm_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Farm_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Farm].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Farm] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Farm] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Farm] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Farm] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Farm] SET ARITHABORT OFF 
GO

ALTER DATABASE [Farm] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Farm] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Farm] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Farm] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Farm] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Farm] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Farm] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Farm] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Farm] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Farm] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Farm] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Farm] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Farm] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Farm] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Farm] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Farm] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Farm] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Farm] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Farm] SET  MULTI_USER 
GO

ALTER DATABASE [Farm] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Farm] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Farm] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Farm] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Farm] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Farm] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Farm] SET  READ_WRITE 
GO

